name: CI Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  check-membership:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify organization membership
        id: check_org_membership
        run: |
          ORG="HiveSoft-UEFS"
          USER="${{ github.event.pull_request.user.login }}"
          RESULT=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          -X POST \
                          -d '{"query":"query { organization(login: \"'"$ORG"'\") { members(first: 100) { nodes { login } } } }"}' \
                          https://api.github.com/graphql)
          if [[ "$RESULT" == *"$USER"* ]]; then
            echo "User is a member of the organization."
          else
            echo "User is not a member of the organization."
            echo $RESULT
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    needs: check-membership

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd app
          npm install

      - name: Build React app
        run: |
          cd app
          npm run build
